# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/gchat.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/gchat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/gchat.proto\"\x1e\n\x0e\x43onnectRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x84\x01\n\x0f\x43onnectResponse\x12%\n\x05state\x18\x03 \x01(\x0e\x32\x16.ConnectResponse.State\x12\x0f\n\x07message\x18\x04 \x01(\t\"9\n\x05State\x12\r\n\tCONNECTED\x10\x00\x12\x10\n\x0c\x44ISCONNECTED\x10\x01\x12\x0f\n\x0bUSER_EXISTS\x10\x02\"!\n\x11\x44isconnectRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"3\n\x12\x44isconnectResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x12SendMessageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"&\n\x13SendMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x13\n\x11GetHistoryRequest\"%\n\x12GetHistoryResponse\x12\x0f\n\x07history\x18\x01 \x01(\t\"\x1d\n\rUpdateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"5\n\x0bUserMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\n\n\x02ts\x18\x03 \x01(\x03\"0\n\x0eUpdateResponse\x12\x1e\n\x08messages\x18\x01 \x03(\x0b\x32\x0c.UserMessage2\x96\x02\n\tGroupChat\x12.\n\x07\x43onnect\x12\x0f.ConnectRequest\x1a\x10.ConnectResponse\"\x00\x12\x37\n\nDisconnect\x12\x12.DisconnectRequest\x1a\x13.DisconnectResponse\"\x00\x12:\n\x0bSendMessage\x12\x13.SendMessageRequest\x1a\x14.SendMessageResponse\"\x00\x12\x37\n\nGetHistory\x12\x12.GetHistoryRequest\x1a\x13.GetHistoryResponse\"\x00\x12+\n\x06Update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.gchat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTREQUEST']._serialized_start=22
  _globals['_CONNECTREQUEST']._serialized_end=52
  _globals['_CONNECTRESPONSE']._serialized_start=55
  _globals['_CONNECTRESPONSE']._serialized_end=187
  _globals['_CONNECTRESPONSE_STATE']._serialized_start=130
  _globals['_CONNECTRESPONSE_STATE']._serialized_end=187
  _globals['_DISCONNECTREQUEST']._serialized_start=189
  _globals['_DISCONNECTREQUEST']._serialized_end=222
  _globals['_DISCONNECTRESPONSE']._serialized_start=224
  _globals['_DISCONNECTRESPONSE']._serialized_end=275
  _globals['_SENDMESSAGEREQUEST']._serialized_start=277
  _globals['_SENDMESSAGEREQUEST']._serialized_end=325
  _globals['_SENDMESSAGERESPONSE']._serialized_start=327
  _globals['_SENDMESSAGERESPONSE']._serialized_end=365
  _globals['_GETHISTORYREQUEST']._serialized_start=367
  _globals['_GETHISTORYREQUEST']._serialized_end=386
  _globals['_GETHISTORYRESPONSE']._serialized_start=388
  _globals['_GETHISTORYRESPONSE']._serialized_end=425
  _globals['_UPDATEREQUEST']._serialized_start=427
  _globals['_UPDATEREQUEST']._serialized_end=456
  _globals['_USERMESSAGE']._serialized_start=458
  _globals['_USERMESSAGE']._serialized_end=511
  _globals['_UPDATERESPONSE']._serialized_start=513
  _globals['_UPDATERESPONSE']._serialized_end=561
  _globals['_GROUPCHAT']._serialized_start=564
  _globals['_GROUPCHAT']._serialized_end=842
# @@protoc_insertion_point(module_scope)
