base_network = "192.168.0."
base_host = 200

Vagrant.configure("2") do |config|
  2.times do |num|
    id = num + 1
    config.vm.define ("vm%01d"  % (id)) do |machine|
      machine.vm.box = "ubuntu/jammy64"
      machine.vm.network "public_network", ip: "#{base_network}#{base_host + id}"
      machine.vm.hostname = "vm#{id}"

      machine.vm.provider "virtualbox" do |vb|
          vb.memory = "2048"
      end

      machine.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get install -y net-tools debconf-utils zip libc-dev-bin build-essential
      SHELL
    end
  end
end
  